### ISSUE TITLE
USER STORY: <HOME PAGE>

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci_pp5_thebodhitree#1]
## User Story:
As a **user** I can **view a landing page with a list of properties** so that **I can see what the business offers**.

## Tasks:

- [x] Create wireframes for landing page
- [x] Create home app with navigation structure
- [x] Create property app with property model and add a few properties
- [x] List featured properties on home page

## Acceptance Criteria:
- Landing page should include a logo and navigation menu suitable across devices
- Landing page should display a carousel of featured properties.
