### ISSUE TITLE
USER STORY: <CREATE A BOOKING>

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci_pp5_thebodhitree#5]
## User Story:
As a **user** I can **create a booking for an accommodation** so that **I can book a stay at the desired accommodation on the desired dates**.

## Tasks:

- [x] Create booking app
- [x] Create booking model
- [x] Create booking form
- [x] Create booking page and set up form submission

## Acceptance Criteria:
- Submitting the form should make the property unavailable and should create a booking on database
- User should enter all relevant information in order to submit the form
