### ISSUE TITLE
USER STORY: <BOOKING MANAGEMENT>

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci_pp5_thebodhitree#6]
## User Story:
As a **user who has booked a stay** I can **retrieve my booking** so that **I can view, edit or cancel my booking**.

## Tasks:

- [x] Link booking to logged in user
- [x] Create my bookings page 
- [x] Create booking details page
- [x] Create retrieve my booking page for users who have not created an account
- [x] Create booking confirmation that displays the booking number to the user for later retrieval
- [x] Create edit and delete functionality

## Acceptance Criteria:
- My bookings page should only be visible for authenticated users
- Clicking on a booking in my bookings will open a booking details page with options to edit and delete
- Retrieve my booking should be available only if the user is not logged in
- Retrieve my booking should request relevant information (booking number from email)
- Supplying correct information in the retrieve my booking page will show the booking detail page with a suggestion to create an account to manage the booking more easily
- Accessing the booking through submitting the retrieve my booking form should allow user to cancel or edit the booking
