### ISSUE TITLE
USER STORY: <REVIEW>

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci_pp5_thebodhitree#9]
## User Story:
As a **previous customer** I can **leave a review of the stay** so that **I can inform future customers about my experience with my booking**.

## Tasks:

- [ ] Create reviews app
- [ ] Create Review Model, Form, view, template urls 
- [ ] Add property reviews to the details page

## Acceptance Criteria:
- Submitting a review should add the review to the database
- The accommodation details page should display the 3 most recent reviews with the option to see more reviews
